### ISSUE TITLE
Nil links in 1.0 - can't modify frozen instance of NilClass

### ISSUE THREAD

**Issue by skwp** [trailblazer/roar#163] opened 2015-10-16 21:50 UTC
In roar 0.12 which we were using previously, you could conditionally not return a link:

``` ruby
link :whatever do
  "thing" if condition
end
```

in Roar 1.0 this apparently ends up throwing a pretty obscure frozen instance of NilClass deep inside representable

``` ruby
  module ModuleExtensions
    # Copies the representable_attrs reference to the extended object.
    # Note that changing attrs in the instance will affect the class configuration.
    def extended(object)
      super
      object.representable_attrs=(representable_attrs) # yes, we want a hard overwrite here and no inheritance.
    end
  end
```

Has anyone experienced this or have any ideas? Should this be filed in the representable project?

**Comment by apotonick** [comment] 2015-10-17 02:09
This is the right place, the `::link` method comes from `Roar::Hypermedia`. :wink: 

Good to know this is needed. I am working on Roar 1.1 atm and will fix it there. BTW, please start testing against Representable/master (2.4) as Roar 1.1 might be requiring >=2.4.

**Comment by skwp** [comment] 2015-10-17 12:36
I believe I tried to load up master represent able but had version conflicts against roar. This fix would be huge for us. Thanks :)

Yan Pritzker  
reverb.com

**Comment by apotonick** [comment] 2015-10-17 21:29
Huge, and fast. It's 120% faster and way simpler internally. 

Thanks for the blog post you guys wrote about Roar a while ago, I wish more OSS users were like that.

**Comment by skwp** [comment] 2015-10-17 22:25
Still a big fan of roar. My one wish is that we can dynamically use Hal or Json api based on headers. If we figure out how to hack that it'll be another good blogpost :)

**Comment by apotonick** [comment] 2015-10-17 22:27
We're working on JSONAPI for Roar 1.1. Once this is through, I don't see why this would be a problem. We can easily do that.

**Comment by skwp** [comment] 2015-10-17 22:38
The way modules are mixed in might be an issue. We probably need to pass that at render time (to_json)

**Comment by apotonick** [comment] 2015-10-17 22:43
Decorators are now the default way of doing it, modules suck as they change objects.

**Comment by skwp** [comment] 2015-10-18 01:04
Yes modules definitely suck. We spent a long time debugging a situation where a mixin overrode a behavior of an object that was used beyond the scope of the represented request. But I'm talking about the HAL mixin, is that now supplied as a decorator also? Is that in 1.1 only?

**Comment by apotonick** [comment] 2015-10-18 01:08
Well you still include the HAL functions in your decorator class, but you'd simply have two decorator classes? Especially since JSONAPI and HAL have totally different DSLs, too.

**Comment by skwp** [comment] 2015-10-18 20:04
Ah, I see. Yeah ideally they have the same DSL and output different formats dynamically. We have hundreds of representers, probably wouldn't want to reimplement everything. I'm going to think of ways this can be made easier :) Sorry to derail this conversation on this bug report

**Comment by skwp** [comment] 2015-10-18 20:13
I tried to write a failing test in roar but it won't fail. It might be a more complex combination of factors. I added: ~/dev/roar/test/hal_links_test.rb

```ruby
      link :nil_link do
        nil
      end
```

But the test passed.

**Comment by skwp** [comment] 2015-10-26 15:21
@apotonick any guidance on trying to get a failing test for the nil links? This is the one thing blocking us from going to version 1.0 of roar. Any ideas would be much appreciated. Thanks!

**Comment by apotonick** [comment] 2015-10-26 23:02
Wait for Roar 1.1. Is that OK?

**Comment by skwp** [comment] 2015-11-01 23:16
Yeah I guess we'll have to wait, much appreciated nick. Is that getting close?

**Comment by apotonick** [comment] 2015-11-01 23:19
If you start writing the blog post _now_ we could release both simultaneously. No pressure :wink: !

Yeah, Representable 2.4 will have a RC release this week.

**Comment by skwp** [comment] 2015-11-01 23:19
:dancer:

**Comment by skwp** [comment] 2015-12-15 16:27
hi @apotonick just circling back on this. does roar 1.1 include a fix for allowing nil links again?

**Comment by skwp** [comment] 2016-01-27 23:25
Still keeping my fingers crossed

**Comment by myabc** [comment] 2016-12-14 23:39
Closing, as can no longer reproduce this issue.

**Closed by myabc** 2016-12-14 23:39 UTC
